# Generated by Django 3.2.10 on 2023-04-22 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('generation', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=250)),
                ('EngCap', models.CharField(max_length=250)),
                ('transmission', models.CharField(max_length=250)),
                ('drive', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('customs_cleared', models.CharField(max_length=50)),
                ('rudder', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('colour', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2100)),
                ('city', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=11, null=True)),
                ('admited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-admited',),
            },
        ),
    ]
