# Generated by Django 3.2.10 on 2023-04-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='run',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
