# Generated by Django 3.2.10 on 2023-04-13 16:36

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('EngCap', models.CharField(max_length=50)),
                ('colour', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('description', models.TextField()),
                ('admited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-admited',),
            },
        ),
    ]
