# Generated by Django 3.2.10 on 2023-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cars_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='customs_cleared',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=2),
        ),
        migrations.AddField(
            model_name='cars',
            name='drive',
            field=models.CharField(choices=[('r', 'rear-wheel drive'), ('f', 'front-wheel drive')], default='r', max_length=2),
        ),
        migrations.AddField(
            model_name='cars',
            name='rudder',
            field=models.CharField(choices=[('r', 'right'), ('l', 'left')], default='r', max_length=2),
        ),
    ]
