# Generated by Django 3.2.10 on 2023-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='drive',
            field=models.CharField(choices=[('r', 'rear-wheel drive'), ('f', 'front-wheel drive'), ('a', 'all-wheel drive')], default='r', max_length=2),
        ),
    ]
