# Generated by Django 3.2.10 on 2023-04-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_cars_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='customs_cleared',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AlterField(
            model_name='cars',
            name='drive',
            field=models.CharField(choices=[('rear-wheel drive', 'rear-wheel drive'), ('front-wheel drive', 'front-wheel drive'), ('all-wheel drive', 'all-wheel drive')], default='rear-wheel drive', max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='rudder',
            field=models.CharField(choices=[('right', 'right'), ('left', 'left')], default='right', max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Mechanic', 'Mechanic')], default='Automatic', max_length=50),
        ),
    ]
