# Generated by Django 3.2.10 on 2023-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20230415_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='EngCap',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cars',
            name='body',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cars',
            name='city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cars',
            name='colour',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cars',
            name='customs_cleared',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(max_length=2100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='drive',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cars',
            name='generation',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cars',
            name='rudder',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.CharField(max_length=250),
        ),
    ]
