# Generated by Django 3.2.10 on 2023-04-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20230420_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='number',
            field=models.CharField(default='null', max_length=11),
        ),
        migrations.AddField(
            model_name='cars',
            name='run',
            field=models.IntegerField(default='null'),
        ),
    ]
