# Generated by Django 3.2.10 on 2023-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20230421_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
