# Generated by Django 3.2.10 on 2023-04-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_cars_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='run',
            field=models.CharField(max_length=20),
        ),
    ]
