# Generated by Django 3.2.10 on 2023-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_cars_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='run',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
