# Generated by Django 3.2.10 on 2023-04-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_run_cars_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='runs',
        ),
    ]
