# Generated by Django 3.2.10 on 2023-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_cars_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='run',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
