# Generated by Django 3.2.10 on 2023-04-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_cars_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='run',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
